# Configure main menu and social menu
[[main]]
identifier = "home"
name = "Página principal"
url = "/"
weight = 1

[main.params]
icon = "home"

[[main]]
name = "Sobre mí"
url = "/about"
weight = 2
identifier = "about"

[main.params]
icon = "about"

#[[main]]
#name = "Buscar"
#url = "/search"
#identifier = "search"
#weight = 3

#[main.params]
#icon = "search"

[[main]]
name = "Entradas"
url = "/archives"
weight = 4
identifier = "archives"

[main.params]
icon = "archives"

[[main]]
name = "Ligas"
url = "/links"
weight = 5
identifier = "links"

[main.params]
icon = "link"




#[[main]]
#name = "Home"
#url = "/"
#weight = 2
#identifier = "home"
#
#[main.params]
#icon = "home"

#[[social]]
#identifier = "github"
#name = "GitHub"
#url = "https://github.com/CaiJimmy/hugo-theme-stack"
#
#[social.params]
#icon = "brand-github"
#
#[[social]]
#identifier = "twitter"
#name = "Twitter"
#url = "https://twitter.com"
#
#[social.params]
#icon = "brand-twitter"

[[social]]
identifier = "youtube"
name = "YouTube"
url = "https://youtube.com/@danielml_mx"
weight = 1

[social.params]
icon = "brand-youtube"

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/danielml-mx"
weight = 2

[social.params]
icon = "brand-github"

